### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by calum-chamberlain** [eqcorrscan/EQcorrscan#104]
This issue describes the steps needed before release 0.2.0.

Note that this release number was chosen because there are significant updates to the API - while the old API generally remains, there is an additional object-oriented layer added to match_filter.

- [x] Finish tests for #94 ;
- [x] Update and check docs;
- [x] Update and check website;
~~- [ ] Get conda installs worked;~~
- [x] Finalise and merge #93 ;
- [x] Check and merge #106 ;
- [x] Check that installs work as documented;
~~- [ ] Work out how to skip tests if download times out;~~
~~- [ ] Work out how to ignore fail for lag-calc at 4.7902.~~

Once this is done the manuscript should get out there.

**Comment by calum-chamberlain** [comment]
OSX needs to use gcc, not clang - gcc in OSX is just a link to clang 👎 Can install gcc via conda though.

**Comment by calum-chamberlain** [comment]
OSX may also need either menlo installed fftw, or info on how to add paths to bashrc.

**Comment by calum-chamberlain** [comment]
Needs a new release before conda upload, but working on it [here](https://github.com/eqcorrscan/staged-recipes).

**Comment by calum-chamberlain** [comment]
See PR: #107
