### ISSUE TITLE
Version 0.3.3

### ISSUE THREAD

**Issue by calum-chamberlain** [eqcorrscan/EQcorrscan#283]
**Its time for a new version of EQcorrscan, first are there any open issues or pull-requests that need to be finished?**

**To-do before release**
- [x] Check docs;
- [x] Make sure changes are represented in `CHANGES.md`;
- [x] Bump version number;
- [x] Merge develop into master; #281 
- [x] Release a release candidate on github;
- [x] Test release candidate on conda-forge: see [pr 4](https://github.com/conda-forge/eqcorrscan-feedstock/pull/4);

If release candidate works on conda-forge then:
- [x] Generate full release on github;
- [x] Get DOI of new version from zenodo and update master README.md
- [x] Release on PyPi;
- [x] Generate PR for eqcorrscan-feedstock from PyPi release;
- [x] Email google-groups email list.
