### ISSUE TITLE
Release 0.4.3

### ISSUE THREAD

**Issue by calum-chamberlain** [eqcorrscan/EQcorrscan#458]
**Its time for a new version of EQcorrscan, first are there any open issues or pull-requests that need to be finished?***

**To-do before release**
- [x] Check docs;
- [x] Make sure changes are represented in `CHANGES.md`;
- [x] Bump version number;
- [x] Merge develop into master;  #457 
- [x] Release a release candidate on github;
- [x] Test release candidate on conda-forge: see [pr 4](https://github.com/conda-forge/eqcorrscan-feedstock/pull/4);

If release candidate works on conda-forge then:
- [x] Generate full release on github;
- [x] Get DOI of new version from zenodo and update master README.md
- [x] Release on PyPi (`python setup.py sdist; python -m twine upload dist/*`);
- [x] Generate PR for eqcorrscan-feedstock from PyPi release;
- [ ] Email google-groups email list.

**Comment by d-chambers** [comment]
Give me a bit more time on #454, it would really help me to have that feature in an official release. I will get to it this afternoon or tomorrow at the latest.

**Comment by calum-chamberlain** [comment]
Okay, I will hold off merging this until a PR for #454 is merged. The main rush from me is I need a new EQcorrscan release to put out the new RT-EQcorrscan release for SSA on Thursday.

**Comment by d-chambers** [comment]
> The main rush from me is I need a new EQcorrscan release to put out the new RT-EQcorrscan release for SSA on Thursday

Ah, that is rather urgent.  I will drop what I am doing now and work on it. If you don't hear from me in the next few hours go ahead and merge without it.
