### ISSUE TITLE
Release 0.4.4

### ISSUE THREAD

**Issue by calum-chamberlain** [eqcorrscan/EQcorrscan#507]
**A new version of EQcorrscan is well overdue, first are there any open issues or pull-requests that need to be finished?***
- [x] #502 - This should be fixed by #500 
- [x] #499 - Windows packaging
- [x] #482 - Reduce excessive output from internal C-funcs
- [x] #479 - Cope with missing phase hints
- [x] #470 - More coping with missing phase hints
- [x] #431 - Calling uniq consistently.
- [x] #504 
- [x] AOB?

**To-do before release**
- [x] Check docs;
- [x] Make sure changes are represented in `CHANGES.md`;
- [x] Bump version number;
- [x] Merge develop into master;
- [x] Release a release candidate on github;
- [x] Test release candidate on conda-forge: see [pr 4](https://github.com/conda-forge/eqcorrscan-feedstock/pull/4);

If release candidate works on conda-forge then:
- [x] Generate full release on github;
- [x] Get DOI of new version from zenodo and update master README.md
- [x] Release on PyPi (`python setup.py sdist; python -m twine upload dist/*`);
- [x] Generate PR for eqcorrscan-feedstock from PyPi release;
- [ ] Email google-groups email list.

**Comment by calum-chamberlain** [comment]
@flixha - this is mostly me trying to keep track of what needs to be done for the next minor release. With the push to develop some much desired new features in #506, #505, ... it would be great if I can squash these issues and push out a 0.4.4 release before we merge in new features.

**Comment by flixha** [comment]
@calum-chamberlain Sounds like the best plan to get this version 0.44 out first. Let me know where I can help here (but would need some extra days as about to leave for fieldwork for 9 days).

**Comment by calum-chamberlain** [comment]
I think I should be able to manage most of this - good luck in the field! Have fun.

**Comment by calum-chamberlain** [comment]
Merge PR see #513

**Comment by calum-chamberlain** [comment]
Test release on conda forge [here](https://github.com/conda-forge/eqcorrscan-feedstock/pull/41)
