### ISSUE TITLE
Prep for v 0.1.4 release.

### ISSUE THREAD

**Issue by calum-chamberlain** [eqcorrscan/EQcorrscan#55]
A lot of work has been done to improve the stability of lag_calc for varying data quality, these changes should be released.  Before the release, the following should be done:
- [x] flake8 checks of all code (include in CI);
- [x] Check docstrings for core modules (ordering and links, see #53):
    - [x] core.subspace
    - [x] core.template_gen
    - [x] core.match_filter
    - [x] core.bright_lights
    - [x] core.lag_calc
- [x] Check docstrings for all utils modules:
    - [x] utils.archive_read
    - [x] utils.catalog_to_dd
    - [x] utils.catalog_utils
    - [x] utils.clustering
    - [x] utils.despike
    - [x] utils.findpeaks
    - [x] utils.mag_calc
    - [x] utils.parameters
    - [x] utils.picker
    - [x] utils.plotting
    - [x] utils.pre_processing
    - [x] utils.sac_util
    - [x] utils.seismo_logs

    ~~- [ ] utils.sfile_util **NOT DOING, migrating to obspy**~~
    - [x] utils.stacking
    - [x] utils.synth_seis
    - [x] utils.trigger
- [x] Remove duplicate functions in match_filter (#51);
- [x] Check tutorial simple examples (#54);
- [x] Add additional tests for edge cases in lag-calc found in #51 (missing data, gaps, overlaps, unprocessed data, reducing cccsums);
- [x] Fix travis CI failing for python 3.4 (issue with matplotlib backend?);
- [x] Use module-level imports where possible;
- [x] Update 'what's new' section in docs;
- [x] Add doc page on how to run the tests;
- [x] Check docs github links.

**Comment by calum-chamberlain** [comment]
Cannot test for decreasing ccc-sums, error message instructs that the error should be reported if it occurs.

**Comment by calum-chamberlain** [comment]
All updated, check that the ci works then release.

**Comment by calum-chamberlain** [comment]
Now a pull request #57
